[NOTAM-2] initial flask and react template implementation
OUCapstone2024GroupDIsForDynamite/notam-app pull request #1
Opened 2024-09-11 18:30 UTC by swagatron300

2024-09-12 20:26 UTC, jamesf31 reviewed
Everything looks straightforward, boilerplate, and basic. Good starting point. Just need to add Jared's comments to the ReadMe.

2024-09-12 20:26 UTC, jamesf31 commented on README.md
> +   ```
Once we add the things for Windows that Jared left on the other code review, this should be set.

2024-09-12 22:54 UTC, Jrubio121 commented on README.md
> +   python3 -m venv venv
Windows command: _python -m venv venv_

2024-09-12 22:54 UTC, Jrubio121 commented on README.md
> +   source venv/bin/activate
Windows command: _venv\Scripts\activate_

2024-09-12 22:55 UTC, Jrubio121 commented on README.md
> +   ```
If you get an authorization error run: _Set-ExecutionPolicy RemoteSigned -Scope CurrentUser_

2024-09-13 18:56 UTC, jamesf31 approved these changes

2024-09-16 19:33 UTC, swagatron300 commented on .DS_Store
.DS_Store is created when the operating system sees that I have looked into a folder with ‘Finder.’ I have added this into the .gitignore.

2024-09-16 19:36 UTC, swagatron300 commented on frontend/package-lock.json
This gets created automatically when npm modifies the node_modules.

2024-09-16 21:43 UTC, tanminivan commented on .DS_Store
Thanks but you will also have to remove the files from this change as well because the gitignore only applies when creating a commit. Let me know if you need help and I can walk you through it.

2024-09-16 21:43 UTC, tanminivan requested changes
Ugh GitHub why do I have to fill this out? I already commented on what I wanted changed

2024-09-18 20:48 UTC, tanminivan approved these changes

2024-09-18 20:51 UTC, Jrubio121 approved these changes

2024-09-18 20:51 UTC, KamidzuKu approved these changes
Approved after meeting Wednesday 9/18/2024

2024-09-18 20:53 UTC, Treeeeeeee approved these changes

2024-09-18 20:54 UTC, merged