[NOTAM-21] Added the build flightpath function
OUCapstone2024GroupDIsForDynamite/notam-app pull request #10
Opened 2024-10-25 20:41 UTC by KamidzuKu

The flightpath function works by using two coordinate class members where the first member is the departure airport and the second is the arrival airport. We then transform coordinates into 2 arrays to use the big circle formula. After choosing the distance between every point from which the notams would be requested we create an incrementation for longitude and latitude to add to the coordinates of the departure airport. We use for loop to create an array of coordinate class members and then return it.

2024-10-28 16:20 UTC, jamesf31 commented on backend/utilities/GeoUtilities.py
> +            coordinates_of_points.append(Coordinate(lat, long)
I could be misinterpreting something here, but doesn't this just return a linear interpolation of points rather than a true flightpath?

2024-10-28 16:20 UTC, jamesf31 commented on backend/utilities/GeoUtilities.py
> +        return coordinates_of_points
Is there a way that we can test this output? Do we know what the flightpath should look like?

2024-10-28 16:20 UTC, jamesf31 commented on backend/utilities/GeoUtilities.py
> +        distance_between_points = 150
This could be a parameter in the function description with a default of 150. I think either way works, but it might be nice to mess with for testing.

2024-10-28 16:20 UTC, jamesf31 commented on backend/utilities/GeoUtilities.py
> +        for i in range(1, number_of_points):
I'm not sure, but should it be number_of_points + 1 since for loops aren't inclusive? Is coordinate_end included in the final array?

2024-10-28 19:49 UTC, swagatron300 commented on backend/utilities/GeoUtilities.py
> +        return coordinates_of_points
Tagging on to James, could we have a testing example in order to see if we truly get the correct flightpath?

2024-10-29 04:58 UTC, tanminivan requested changes

2024-10-29 04:58 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +        #turn the Coordinate class instance into an array to support the inputs of the great circle function requirements
Those aren't arrays, they're tuples.

2024-10-29 04:58 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +        #calculate coordinates of each place to request notams excluding the initial and final airport coordinates
This comment would be a good place to write WHY you are excluding the initial and final airport coords.

2024-10-29 04:58 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +        coordinates_of_points = []
`coordinates_of_points` but points _are_ coordinates...

2024-10-29 04:58 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +            coordinates_of_points.append(Coordinate(lat, long)
Missing a closing paren here

2024-10-29 04:58 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +        coordinate_a = (coordinate_start.longtitude, coordinate_start.latitude)
longtitude

2024-10-29 04:58 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +        coordinate_b = (coordinate_end.longtitude, coordinate_end.latitude)
What good does this do to create `coordinate_a` and `coordinate_b`? Is `coordinate_a[0]` REALLY more clear than `coordinate_start.longitude`?

2024-10-29 04:58 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +        #calculate the distance between two given airports in miles
statue miles? nautical miles?

2024-10-31 04:33 UTC, tanminivan requested changes
I think my request changes got wiped out when reviewers were added to this PR

2024-11-06 21:26 UTC, jamesf31 commented on backend/utilities/GeoUtilities.py
> +        coordinate_a = (coordinate_start.longtitude, coordinate_start.latitude)
This is the main thing that I was thinking we might need to fix before merging. Does this code work with this typo? I haven't checked out the branch.

2024-11-06 21:34 UTC, Treeeeeeee approved these changes

2024-11-07 18:21 UTC, swagatron300 approved these changes

2024-11-08 14:22 UTC, jamesf31 approved these changes

2024-11-08 14:31 UTC, tanminivan requested changes

2024-11-08 14:31 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +    def build_flight_path(self, coordinate_start, coordinate_end, distance_between_points):
I thought `distance_between_points` was going to be a keyword argument with a default, like `distance_between_points=150` ?

2024-11-08 14:31 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +            flightpath_coordinates.append(Coordinate(lat, long))
Okay, just so I am in the loop, the plan is to use this simple (albeit incorrect) calculation here in NOTAM-21 and to do the correct implementation in NOTAM-43?

2024-11-08 18:10 UTC, KamidzuKu commented on backend/utilities/GeoUtilities.py
> +            flightpath_coordinates.append(Coordinate(lat, long))
Yes

2024-11-11 18:17 UTC, tanminivan requested changes

2024-11-11 18:17 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +from geopy.distance import great_circle #function to calculate the distances on the earth surface between 2 coordinates
You use `geopy` but forgot to add it to requirements.txt.

2024-11-11 18:17 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +        def distance_between_points(dbp=150):
Why not do:

```python
def build_flight_path( self, coordinate_start, coordinate_end, distance_between_points=150 )
```

?

What does adding a nested function in here add for you?

2024-11-11 18:17 UTC, tanminivan commented
You have some conflicts that need to be resolved, please be sure to squash and rebase so you can resolve these conflicts.

2024-11-11 18:20 UTC, tanminivan requested changes
Tested on `main` and app works. I switch to this branch and it blows up when attempting to get a flight path from OKC to BOS.

```
/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/geopy/point.py:472: UserWarning: Latitude normalization has been prohibited in the newer versions of geopy, because the normalized value happened to be on a different pole, which is probably not what was meant. If you pass coordinates as positional args, please make sure that the order is (latitude, longitude) or (y, x) in Cartesian terms.
  return cls(*args)
127.0.0.1 - - [11/Nov/2024 12:18:45] "GET /api/notam/OKC/BOS HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/brian/git/notam-app/backend/app.py", line 31, in generate_flight_briefing
    flightpath_coords = geo_utils.build_flight_path(airport_a_coor, airport_b_coor)
  File "/home/brian/git/notam-app/backend/utilities/GeoUtilities.py", line 52, in build_flight_path
    distance_between_airports = great_circle((coordinate_start.longitude, coordinate_start.latitude), (coordinate_end.longitude, coordinate_end.latitude)).miles
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/geopy/distance.py", line 461, in __init__
    super().__init__(*args, **kwargs)
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/geopy/distance.py", line 276, in __init__
    kilometers += self.measure(a, b)
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/geopy/distance.py", line 464, in measure
    a, b = Point(a), Point(b)
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/geopy/point.py", line 175, in __new__
    return cls.from_sequence(seq)
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/geopy/point.py", line 472, in from_sequence
    return cls(*args)
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/geopy/point.py", line 188, in __new__
    _normalize_coordinates(latitude, longitude, altitude)
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/geopy/point.py", line 74, in _normalize_coordinates
    raise ValueError('Latitude must be in the [-90; 90] range.')
ValueError: Latitude must be in the [-90; 90] range.
```

2024-11-11 20:43 UTC, tanminivan commented
New error after the latest commit:

```
127.0.0.1 - - [11/Nov/2024 14:39:59] "GET /api/notam/OKC/BOS HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/brian/git/notam-app/backend/venv/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/brian/git/notam-app/backend/app.py", line 31, in generate_flight_briefing
    flightpath_coords = geo_utils.build_flight_path(airport_a_coor, airport_b_coor)
  File "/home/brian/git/notam-app/backend/utilities/GeoUtilities.py", line 65, in build_flight_path
    coordinates.append(coordinate_end)
NameError: name 'coordinates' is not defined
```

Please don't make the rest of the team test your changes. Test them first locally before you ask people to review them.

2024-11-11 21:21 UTC, tanminivan commented
Can confirm that I can run without errors, thanks.

I want to see the final push that is squashed and rebased with the merge conflicts resolved before approving.

2024-11-11 21:21 UTC, tanminivan requested changes

2024-11-11 21:21 UTC, tanminivan commented on backend/config.py
> +CLIENT_SECRET = "30980dC5B1c549f18bf9923F81748298"  # Replace with your actual client secret
oopsies

2024-11-11 22:27 UTC, tanminivan approved these changes

2024-11-11 22:28 UTC, merged