[Notam-33] Remove repeated notams
OUCapstone2024GroupDIsForDynamite/notam-app pull request #14
Opened 2024-10-30 17:06 UTC by jamesf31

2024-10-31 03:48 UTC, tanminivan commented on backend/utilities/NotamUtilities.py
> +        for i in range (len(notams)):
Why not just use a set?

2024-10-31 03:48 UTC, tanminivan commented on backend/tests/test_NotamUtilities.py
> +        notams = self.NotamFetcher.fetch_by_coordinates(coordinates)
I think it's generally not advisable to make live API calls in unit tests. Unit tests are supposed to be run often and you want to avoid spamming the API with many, many calls. Also, you don't want to fail unit tests because the API is down or you have an expired auth key or whatever. You can unknowingly get caught testing the wrong thing.

What about creating some very obvious identical synthetic notam objects and ensuring that they are deduplicated?

2024-10-31 13:42 UTC, jamesf31 commented on backend/utilities/NotamUtilities.py
> +        for i in range (len(notams)):
I tried this first. Since the notam objects are distinct, even when their meta data is exactly the same, using a set didn't remove any notams. I'm open to other implementation ideas, though.

2024-10-31 13:43 UTC, jamesf31 commented on backend/tests/test_NotamUtilities.py
> +        notams = self.NotamFetcher.fetch_by_coordinates(coordinates)
This makes sense. I'll change it.

2024-10-31 14:43 UTC, tanminivan commented on backend/utilities/NotamUtilities.py
> +        for i in range (len(notams)):
Override the equality function for the Notam class?

2024-10-31 18:13 UTC, jamesf31 commented on backend/utilities/NotamUtilities.py
> +        for i in range (len(notams)):
Done

2024-10-31 19:00 UTC, swagatron300 approved these changes

2024-11-04 22:00 UTC, tanminivan requested changes

2024-11-04 22:00 UTC, tanminivan commented on backend/utilities/NotamUtilities.py
> +        new_notams = list(set(notams))
Why all this code around taking a list, creating a set out of it and turning it into a list again? Why not just store the notams in a set to begin with?

2024-11-04 22:14 UTC, jamesf31 commented on backend/utilities/NotamUtilities.py
> +        new_notams = list(set(notams))
Fair enough, haha. I was trying to follow the original software design, but I changed it to be more straightforward. Let me know if the new implementation makes sense.

2024-11-04 22:40 UTC, tanminivan approved these changes

2024-11-04 22:40 UTC, tanminivan commented on backend/utilities/NotamFetcher.py
>          return notams
Not sure if you want to pass around a set or a list from here on out, but you could do `return list(notams)`

2024-11-04 22:40 UTC, tanminivan commented on backend/utilities/NotamUtilities.py
> +        new_notams = list(set(notams))
Yep, I understand the hesitancy to throw away code you've already written. But sometimes the more code you can take out, the better.

2024-11-05 19:43 UTC, Jrubio121 approved these changes

2024-11-06 02:51 UTC, Treeeeeeee approved these changes

2024-11-06 15:05 UTC, merged