NOTAM-49: Add importance field to Notam class
OUCapstone2024GroupDIsForDynamite/notam-app pull request #18
Opened 2024-11-11 23:14 UTC by jamesf31

2024-11-12 05:00 UTC, tanminivan requested changes

2024-11-12 05:00 UTC, tanminivan commented on backend/objects/Notam.py
> +        # Initialize Importance
I think this would be a good place to comment how this field is supposed to be used. Float between 0 and 1? Int between 0 and 1000? No limit? Higher is more important? Lower is more important?

What about using this field to actually sort Notam objects? How is that handled in python?

What about some unit tests where we initialize some synthetic notams and verify that they sort correctly?

2024-11-15 00:03 UTC, tanminivan approved these changes

2024-11-15 00:03 UTC, tanminivan commented on backend/tests/test_NotamImportance.py
> +        notam1= Notam('{"properties": {"coreNOTAMData": {"notam": {"id": "NOTAM_1_74112747"}}}}')
It's probably be a bit more clear if you named these with the importance that it'll have.

`notam_1` = importance 1
`notam_2` = importance 2

2024-11-15 15:12 UTC, jamesf31 commented on backend/tests/test_NotamImportance.py
> +        notam1= Notam('{"properties": {"coreNOTAMData": {"notam": {"id": "NOTAM_1_74112747"}}}}')
Changed!

2024-11-15 20:00 UTC, Treeeeeeee approved these changes

2024-11-17 00:39 UTC, swagatron300 approved these changes

2024-11-17 07:45 UTC, KamidzuKu approved these changes

2024-11-17 20:46 UTC, merged