NOTAM-10: Hook Up React and Flask with Dummy Data
OUCapstone2024GroupDIsForDynamite/notam-app pull request #2
Opened 2024-09-19 19:46 UTC by Jrubio121

2024-09-19 20:30 UTC, jamesf31 commented on backend/app.py
> +    response.headers['Access-Control-Allow-Origin'] = '*'
![image](https://github.com/user-attachments/assets/7f6eff91-5a7e-4b70-9f05-f98eb0e5039c)
This line causes an error on my machine. This could be my fault, but I installed the requirement.txt and everything.

2024-09-19 21:40 UTC, jamesf31 approved these changes
Code looks straightforward and works well. Approved.

2024-09-19 23:40 UTC, swagatron300 commented
All looks good to me.

2024-09-19 23:41 UTC, swagatron300 approved these changes

2024-09-20 03:06 UTC, tanminivan requested changes

2024-09-20 03:06 UTC, tanminivan commented on backend/app.py
> +    response.headers['Access-Control-Allow-Headers'] = 'Content-Type, Authorization'
These headers are repeated in `get_notams` above. Can this be refactored so that we only have to define these standard response headers once? If we duplicate this for every endpoint it could be unwieldy and easy to miss if a change to those headers were ever needed.

2024-09-24 22:25 UTC, tanminivan approved these changes

2024-09-24 23:16 UTC, jamesf31 approved these changes

2024-09-25 06:02 UTC, Treeeeeeee approved these changes

2024-09-25 20:05 UTC, merged