[NOTAM-43] Added the full flightpath and added math into requirements
OUCapstone2024GroupDIsForDynamite/notam-app pull request #21
Opened 2024-11-18 21:34 UTC by KamidzuKu

Added the full flightpath calculations

2024-11-20 22:05 UTC, tanminivan commented
Hmm, this doesn't look quite right:

![image](https://github.com/user-attachments/assets/32cd4777-52da-4738-bbf5-bfb3eb7bed51)

2024-11-23 06:14 UTC, tanminivan requested changes
coordinates don't look correct

2024-11-25 17:53 UTC, jamesf31 requested changes
What Brian said. Like I said in our last meeting, it would be great to have some tests so we can check the accuracy of the function without having to go through this whole rigamarole.

2024-11-25 17:53 UTC, jamesf31 commented on backend/utilities/GeoUtilities.py
> +            lng = math.atan2(y, x)
As a bandaid fix, you could change this to something like lng = -1*math.abs( longitude ) since everything in the continental US will have a negative longitude.

2024-11-25 18:31 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +            lng = math.atan2(y, x)
> As a bandaid fix, you could change this to something like lng = -1*math.abs( longitude ) since everything in the continental US will have a negative longitude.

What are the advantages/disadvantages of such a fix?

2024-11-25 20:25 UTC, jamesf31 commented
![image](https://github.com/user-attachments/assets/eb33d11e-31a8-405d-8177-f02298203186)
HNL to BOS

2024-11-25 22:15 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +            flightpath_coordinates.append(self.intermediate_point(coordinate_start.latitude, coordinate_start.longitude, coordinate_end.latitude, coordinate_end.longitude, i/number_of_points))
You could clean up this long call by just passing `Coordinate` objects to `intermediate_point()` instead of its individual components.

2024-11-25 22:16 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +    def intermediate_point(self, lat1, lng1, lat2, lng2, f):
Not really a fan of single letter parameter names, especially when `f` is usually interpreted as a function/lambda.

2024-11-25 22:31 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +        lng = math.atan2(y, x)
am I missing where the sign flip happened? This looks the same as what it was previously. Did I have a bad test?

2024-11-26 18:49 UTC, jamesf31 commented on backend/utilities/GeoUtilities.py
> +        lng = math.atan2(y, x)
Yeah, I spend a while scouring the diff before just switching back to the old commit. I ran it myself and got:
![image](https://github.com/user-attachments/assets/7745975d-57f7-4843-9fd0-eb9c1a41233a)
Which lines up pretty closely to what I get from my commit. Now I'm curious about what you ran, I was just trusting you blindly haha

2024-11-26 18:53 UTC, jamesf31 approved these changes

2024-11-26 18:55 UTC, Treeeeeeee approved these changes

2024-11-27 05:14 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +        lng = math.atan2(y, x)
Hmm, weird. Check out the branch `add-geo-tester`. I wrote a small utility at `backend/tester.py` that initializes GeoUtilities, fetches the coordinates of a flight path, then prints them out. Then I took that output and plugged it into my mapper. Maybe I made a mistake at the mapping part?

But when I run the tester today I get negative longitudes.

2024-11-27 05:19 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +        lng = math.atan2(y, x)
Ah, okay, it was me and a problem with my mapper. I read coordinates from a file but then hardcoded a negative for the longitude when mapping, so that made the longitude positive when mapping. derp. I remember making that change as a quick fix to verify that it was only the sign tha twas wrong, but somewhere along the line it got committed. Oops! This is what I get for being lazy.

For the curious, this is the path I ended up with (this is going off of what is in `main` currently):
![image](https://github.com/user-attachments/assets/80f5ce2f-1ee4-4580-a145-577e8fa9ba6b)

2024-11-27 16:01 UTC, merged