Notam 5: Query FAA API
OUCapstone2024GroupDIsForDynamite/notam-app pull request #3
Opened 2024-09-26 16:38 UTC by swagatron300

2024-09-26 21:08 UTC, jamesf31 commented on frontend/src/components/NotamCard.js
> +  const [location, setLocaion] = useState("");
Should this be "location, setLocation" ?

2024-09-26 21:09 UTC, jamesf31 commented on frontend/src/components/NotamCard.js
> +    setLocaion(e.target.value);
Should this be "setLocation" ?

2024-09-26 21:18 UTC, jamesf31 commented on backend/app.py
> +from flask_cors import CORS
flask_cors isn't in requirements, so I had to download this manually

2024-09-26 21:19 UTC, jamesf31 commented on backend/app.py
> +import requests
requests also isn't in requirements, so I downloaded manually.

2024-09-26 21:26 UTC, jamesf31 commented on frontend/src/components/NotamCard.js
>            placeholder="Enter NOTAM number"
Might as well change this to "Enter an ICAO Location"
![image](https://github.com/user-attachments/assets/c8066ae8-3ea9-4f0c-a64f-2c2e19be79de)

2024-09-26 21:30 UTC, jamesf31 commented on backend/app.py
> +def fetch_notam(icao_location, response_format='geoJson'):
Do we want to use icao_location, or just domesticLocation?

2024-09-26 22:43 UTC, swagatron300 commented on frontend/src/components/NotamCard.js
> +  const [location, setLocaion] = useState("");
lol, yes

2024-09-26 22:51 UTC, swagatron300 commented on backend/app.py
> +def fetch_notam(icao_location, response_format='geoJson'):
From googling, I found its possible for two airports to share the last 3 digits of a location, so I used ICAO since there are no two ICAO tags that are the same.

2024-09-26 22:53 UTC, swagatron300 commented on frontend/src/components/NotamCard.js
>            placeholder="Enter NOTAM number"
Initially added the examples just in case anyone didn’t know an ICAO location example.

2024-09-30 01:12 UTC, Jrubio121 approved these changes
Looks good I think James touched on everything I noticed.

2024-09-30 14:01 UTC, jamesf31 commented on frontend/src/components/NotamCard.js
>            placeholder="Enter NOTAM number"
Yeah I think that the examples are a great idea! I just meant to change where it says "Enter NOTAM number" since we are now querying by location. Not a big deal either way.

2024-10-01 03:15 UTC, tanminivan commented
As we discussed in our meeting Monday, you'll definitely want to rebase branch off of the latest main so you can drop the outdated NOTAM-10 commits that are in here. I likely commented on some of that code since it's all mixed together.

2024-10-01 03:15 UTC, tanminivan requested changes

2024-10-01 03:15 UTC, tanminivan commented on backend/app.py
> +CORS(app)
What does this do?

2024-10-01 03:15 UTC, tanminivan commented on backend/app.py
> +# New endpoint to return specific NOTAM data based on the number
"based on the number" but the route says "location" as well as the function parameter. This could lead to some confusion.

2024-10-01 03:15 UTC, tanminivan commented on backend/app.py
> +def fetch_notam(icao_location, response_format='geoJson'):
`fetch_notam`, as in, a _single_ notam?

2024-10-01 03:15 UTC, tanminivan commented on backend/app.py
> +def get_notam(location):
`get_notam()`, as in, a _single_ notam?

2024-10-01 03:15 UTC, tanminivan commented on backend/app.py
> +        return None
So in this case, there's no way to let the user know that something exceptional happened? You just get zero notams?

2024-10-01 03:15 UTC, tanminivan commented on backend/app.py
> +        response.raise_for_status()  # Raise an error for bad responses
Is this only non-HTTP 200 responses?

2024-10-01 03:15 UTC, tanminivan commented on backend/app.py
> +        print(BASE_URL)
Could remove some debug print statements.

2024-10-01 03:15 UTC, tanminivan commented on backend/app.py
> +        'client_secret': CLIENT_SECRET
What happens if these are null?

2024-10-01 03:15 UTC, tanminivan commented on backend/app.py
> +        'icaoLocation': icao_location,
Is this input sanitized?

2024-10-01 03:15 UTC, tanminivan commented on backend/app.py
> +        notam_list = [item['properties']['coreNOTAMData']['notam'] for item in data['items']]
Are you sure you are getting all the notams this way?

2024-10-01 03:15 UTC, tanminivan commented on frontend/package.json
Already not a fan of these files :) Hopefully they dont change with EVERY pull request.

2024-10-01 03:15 UTC, tanminivan commented on frontend/src/components/NotamCard.js
> +  const [location, setLocaion] = useState("");
locaion

2024-10-01 03:15 UTC, tanminivan commented on frontend/src/components/NotamCard.js
> +    e.preventDefault(); // Prevent form from submitting the default way
What _is_ the default way? :)

2024-10-01 03:15 UTC, tanminivan commented on frontend/src/components/NotamCard.js
> +        console.log(data)
debug logging?

2024-10-01 03:15 UTC, tanminivan commented on frontend/src/components/NotamCard.js
> +        setError("NOTAM not found"); // Set error message
Um, are you sure that the error will be "notam not found" if the response is anything other than "OK"?

2024-10-01 03:15 UTC, tanminivan commented on frontend/src/components/NotamCard.js
> +      setError("An error occurred while fetching the NOTAM."); // Set error message for any fetch errors
But what is the error? We log it to the console but not to the user.

2024-10-01 03:15 UTC, tanminivan commented on frontend/src/pages/LandingPage.js
> +        <h1>Welcome to the Landing Page</h1>
I love puns

2024-10-01 03:15 UTC, tanminivan commented on frontend/webpack.config.js
Do you actually modify this file or was this some auto-generated stuff?

2024-10-02 19:36 UTC, swagatron300 commented on backend/app.py
> +def fetch_notam(icao_location, response_format='geoJson'):
I assume pilots will be the one using out app, so pilots should know ICAO tags.

2024-10-02 19:37 UTC, swagatron300 commented on backend/config.py
> +CLIENT_SECRET = ""  # Replace with your actual client secret
I assume pilots will be the one using out app, so pilots should know ICAO tags. Ticket created to refactor config.py.

2024-10-02 19:41 UTC, swagatron300 commented on backend/app.py
> +def fetch_notam(icao_location, response_format='geoJson'):
Correct.

2024-10-02 19:41 UTC, swagatron300 commented on backend/app.py
> +def get_notam(location):
Correct.

2024-10-02 19:51 UTC, swagatron300 commented on backend/app.py
> +        return None
There a print statement to the screen, how else would I let them know?

2024-10-02 19:59 UTC, swagatron300 commented on backend/app.py
> +        response.raise_for_status()  # Raise an error for bad responses
Yes.

2024-10-02 20:03 UTC, swagatron300 commented on frontend/package.json
Files should not change, once all dependencies are listed it wont be altered.

2024-10-02 20:12 UTC, swagatron300 commented on backend/app.py
> +        'client_secret': CLIENT_SECRET
Will receive a 401 error for unauthorized access.

2024-10-02 20:25 UTC, Treeeeeeee approved these changes

2024-10-02 20:49 UTC, swagatron300 commented on backend/app.py
> +        'icaoLocation': icao_location,
No, just added some regex to match the location format, also added a CLIENt_SECRET ValueError.

2024-10-02 20:54 UTC, swagatron300 commented on backend/app.py
> +        notam_list = [item['properties']['coreNOTAMData']['notam'] for item in data['items']]
I get all NOTAMs based off of a singular NOTAM location. As long as the NOTAM has a parameter of 'icaolocation' I should receive the data I wanted to display in the NotamCard.js file.

2024-10-02 20:59 UTC, swagatron300 commented on frontend/src/components/NotamCard.js
> +    e.preventDefault(); // Prevent form from submitting the default way
Default behavior is when the page will reload or refresh and send an HTTP request to the URL, this results in a full page reload and sends data to the server. I don't want it to reload the full page.

2024-10-02 21:02 UTC, jamesf31 commented on backend/app.py
> +        notam_list = [item['properties']['coreNOTAMData']['notam'] for item in data['items']]
Hmm I'm actually remembering from when I was messing around with the API that it might be separated into pages that cap at around 50 NOTAMs. I think with the query you can change the page length with a header, or we can query with a while loop until there are no more pages left and concatenate to the response.
I could also be wrong, I can't remember super specifically. Worth looking into, though.

2024-10-02 21:04 UTC, jamesf31 commented on backend/app.py
> +def fetch_notam(icao_location, response_format='geoJson'):
@tanminivan While looking into NOTAM-20, I found that IATA locations have three characters while ICAO locations have four. So, we could allow for querying based off either (once we are converting to lat and long) by having a simple filter based on three or four character queries in the geo_resolve function. For now, this definitely works.

2024-10-02 21:06 UTC, jamesf31 commented on backend/app.py
> +        'icaoLocation': icao_location,
This can be fixed in the geo_resolve function as well, rather than worrying about it on this ticket. Eventually, we will be querying off lat and long which will be sanitized by geo_resolve.

2024-10-03 00:11 UTC, swagatron300 commented on frontend/src/components/NotamCard.js
> +        setError("NOTAM not found"); // Set error message
Added more errors for 404,400 and 500 responses.

2024-10-03 00:22 UTC, swagatron300 commented on backend/app.py
> +        notam_list = [item['properties']['coreNOTAMData']['notam'] for item in data['items']]
Good catch James, I'll look into that.

2024-10-03 01:15 UTC, tanminivan approved these changes

2024-10-03 01:16 UTC, tanminivan commented on backend/app.py
> +        'client_secret': CLIENT_SECRET
We could probably add a check here and warn the user if it's not configured instead of relying on the API to block us.

2024-10-03 01:19 UTC, jamesf31 approved these changes
Looking good.

2024-10-03 23:03 UTC, swagatron300 commented on backend/app.py
> -    notam = mock_data.get(notam_number)
Here is the dummy data I decided to delete.

2024-10-03 23:13 UTC, merged