[NOTAM-20] Find Coordinates for Airport Codes
OUCapstone2024GroupDIsForDynamite/notam-app pull request #5
Opened 2024-10-02 23:26 UTC by jamesf31

2024-10-03 00:26 UTC, Jrubio121 commented on backend/utilities/GeoUtilities.py
> +        if(len(airport) == 3):
What is 3? Maybe make this a variable to define what it is for clarity.

2024-10-03 00:26 UTC, Jrubio121 commented on backend/utilities/GeoUtilities.py
> +        if(len(airport) == 4):
Same here

2024-10-03 00:50 UTC, jamesf31 commented on backend/utilities/GeoUtilities.py
> +        if(len(airport) == 3):
I realized that I could just combine this statement. Fixed.

2024-10-03 00:50 UTC, jamesf31 commented on backend/utilities/GeoUtilities.py
> +        if(len(airport) == 4):
See above

2024-10-03 01:15 UTC, swagatron300 commented on backend/utilities/GeoUtilities.py
> +        self.iata_codes = {}  # A dictionary to store iata codes and their coordinates
iata

2024-10-03 01:17 UTC, jamesf31 commented on backend/utilities/GeoUtilities.py
> +        self.iata_codes = {}  # A dictionary to store iata codes and their coordinates
Am I missing a typo here?

2024-10-03 01:19 UTC, swagatron300 commented on backend/tests/test_GeoUtilities.py
> +        """Test getting a coordinate for a valid IATA code."""
Whats IATA?

2024-10-03 01:21 UTC, jamesf31 commented on backend/tests/test_GeoUtilities.py
> +        """Test getting a coordinate for a valid IATA code."""
IATA is the other method of recording airport codes other than ICAO. When you query a NOTAM with "domesticLocation" instead of "IcaoLocation", it queries based on the IATA code, as far as I know.

2024-10-03 01:37 UTC, Treeeeeeee approved these changes

2024-10-03 02:08 UTC, swagatron300 approved these changes

2024-10-03 16:14 UTC, Jrubio121 approved these changes

2024-10-03 21:55 UTC, tanminivan requested changes

2024-10-03 21:55 UTC, tanminivan commented on backend/tests/test_GeoUtilities.py
> +        """Test getting a coordinate for a valid ICAO code."""
I'd probably split these up into two separate tests, `test_valid_iata_coordinate` and `test_valid_icao_coordinate`

2024-10-03 21:55 UTC, tanminivan commented on backend/tests/test_GeoUtilities.py
> +        self.assertEqual(coordinate.latitude, 35.3931)
What if you have some rounding error here?

2024-10-03 21:55 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +            print(f"Error: The file {self.file_path} does not exist.")
Throw the exception, you don't want to continue on at this point, do you?

2024-10-03 21:55 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +            print(f"An error occurred: {e}")
Same here

2024-10-03 21:55 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +        return self.icao_codes.get(airport) or self.iata_codes.get(airport)
So you are supporting both IATA and ICAO? Why is that?

2024-10-03 21:55 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +            raise ValueError(f"Airport code '{airport}' not found in IATA or ICAO data.")
Is ValueError the best exception here?

2024-10-03 21:55 UTC, tanminivan commented on backend/tests/__init__.py
gotta love python and how you have to put an empty file here

2024-10-03 21:55 UTC, tanminivan commented on backend/csvs/iata-icao-lat-long.csv
WHere did this come from? How should it be updated in the future if needs to be kept up to date?

2024-10-03 22:15 UTC, jamesf31 commented on backend/utilities/GeoUtilities.py
> +            print(f"Error: The file {self.file_path} does not exist.")
Yep, great point.

2024-10-03 23:56 UTC, jamesf31 commented on backend/utilities/GeoUtilities.py
> +        return self.icao_codes.get(airport) or self.iata_codes.get(airport)
We haven't discussed this yet, so I felt like allowing both (at least for now) would allow for the most flexibility.

I also know that some IATA codes don't have ICAO codes (especially very small airports) and possibly vice versa. So, this allows all airports to be queried.

2024-10-03 23:57 UTC, jamesf31 commented on backend/tests/__init__.py
yep..

2024-10-03 23:58 UTC, jamesf31 commented on backend/csvs/iata-icao-lat-long.csv
I put on the ticket in Jira a link to the repo where it came from.

I guess the practices for updating this would be the same as any other feature, i.e., a ticket with a code review to ensure integrity.

2024-10-03 23:59 UTC, jamesf31 commented on backend/utilities/GeoUtilities.py
> +            raise ValueError(f"Airport code '{airport}' not found in IATA or ICAO data.")
Ah, I see now that there is a specific KeyError code. I will change it to that.

2024-10-04 00:00 UTC, jamesf31 commented on backend/tests/test_GeoUtilities.py
> +        self.assertEqual(coordinate.latitude, 35.3931)
I guess that I could round both to two decimal places, if we consider that "close enough"?

2024-10-04 00:23 UTC, jamesf31 commented on backend/tests/test_GeoUtilities.py
> +        """Test getting a coordinate for a valid ICAO code."""
Done

2024-10-04 00:23 UTC, jamesf31 commented on backend/tests/test_GeoUtilities.py
> +        self.assertEqual(coordinate.latitude, 35.3931)
I did this ^^. Let me know if you would prefer a different solution and I can re-implement.

2024-10-04 00:23 UTC, jamesf31 commented on backend/utilities/GeoUtilities.py
> +            print(f"Error: The file {self.file_path} does not exist.")
done.

2024-10-04 00:23 UTC, jamesf31 commented on backend/utilities/GeoUtilities.py
> +            print(f"An error occurred: {e}")
Done

2024-10-04 00:23 UTC, jamesf31 commented on backend/utilities/GeoUtilities.py
> +            raise ValueError(f"Airport code '{airport}' not found in IATA or ICAO data.")
Done.

2024-10-04 00:26 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +        return self.icao_codes.get(airport) or self.iata_codes.get(airport)
Definitely put in a ticket to have a follow up conversation about this to revisit it.

2024-10-04 00:27 UTC, tanminivan commented on backend/tests/test_GeoUtilities.py
> +        self.assertEqual(coordinate.latitude, 35.3931)
Looks good

2024-10-04 00:30 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +            raise FileNotFoundError(f"Error: The file {self.file_path} does not exist.")
I'd log something helpful for you and then raise the original exception, which may have more info than the new exception you are creating here.

```python
except FileNotFoundError as e:
    print( "Couldn't find {self.file_path}. Does it exist?" )
    raise e
```

2024-10-04 00:30 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +            raise BaseException(f"An error occurred: {e}")
Same here as well

2024-10-04 00:30 UTC, tanminivan commented on backend/utilities/GeoUtilities.py
> +            raise ValueError(f"Airport code '{airport}' not found in IATA or ICAO data.")
You could also create your own exceptions too!

2024-10-04 00:30 UTC, tanminivan commented on backend/csvs/iata-icao-lat-long.csv
You could also document in a `README.md` where it comes from and how to update it. Sometimes you migrate ticketing systems and they may not be around forever...

2024-10-04 00:31 UTC, tanminivan approved these changes

2024-10-04 00:32 UTC, jamesf31 commented on backend/utilities/GeoUtilities.py
> +        return self.icao_codes.get(airport) or self.iata_codes.get(airport)
[Ticket](https://capstonefall24.atlassian.net/jira/software/projects/NOTAM/boards/1/backlog?selectedIssue=NOTAM-31&atlOrigin=eyJpIjoiZjRkYzA5MjFhNjQxNDM1YWE1NDk2NzFmYmQ3MTlhNWIiLCJwIjoiaiJ9)

2024-10-04 00:54 UTC, jamesf31 commented on backend/utilities/GeoUtilities.py
> +            raise FileNotFoundError(f"Error: The file {self.file_path} does not exist.")
Done!

2024-10-04 00:58 UTC, jamesf31 commented on backend/csvs/iata-icao-lat-long.csv
Forgot this here. Would be a good idea for sure. I might create a ticket for a readme revamp.

2024-10-04 01:06 UTC, merged